### ISSUE TITLE
non-ascii characters not parsed correctly in data description interface

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-packager#14]
# Description

It seems that non-ascii characters are not ready correctly in some places. See "AÑO" > "A O" example in screenshot below.

# Tasks

* [x] Fix handling on non-ascii characters

<img width="1280" alt="screenshot 2015-11-15 15 21 51" src="https://cloud.githubusercontent.com/assets/791678/11168915/f07c30de-8bac-11e5-8235-8e790a6f15bd.png">

**Comment by kravets-levko** [comment]
'Accidentally' fixed within other task.
