### ISSUE TITLE
Update fiscalPeriod to create object rather than string

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-packager#29]
`fiscalPeriod` is no longer a string in the spec; it is now an object.  See [here](https://github.com/openspending/fiscal-data-package/commit/c4fb83b27c4617b1d2dda89af1ecf7376b460e77) and [here](https://github.com/dataprotocols/schemas/commit/fb1d1200e5129249a54894938bf44cdef93afbb9#diff-b4feb709bbce9304b27f08b44582b535).

![screen shot 2015-11-25 at 14 44 00](https://cloud.githubusercontent.com/assets/772616/11396534/2e33bdec-9383-11e5-88a3-c98bc541b3f2.png)

**Comment by pwalsh** [comment]
FIXED.
