### ISSUE TITLE
No option to fix strange type guesses

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-packager#33]
![screen shot 2015-11-27 at 18 38 03](https://cloud.githubusercontent.com/assets/772616/11444471/3e0eb7bc-9536-11e5-8284-05e9126fb785.png)

In this column, `APPROVED` is 0 pretty often. This causes the type guesser to guess it is boolean.  This is probably actually an [issue for jsontableschema-js](https://github.com/okfn/jsontableschema-js/issues), but the UI doesn't give an option for correcting to integer given the limited set of options (boolean or string).  These values (and "any") don't allow for the possibility of mapping the field to an "Amount" concept.

![screen shot 2015-11-27 at 18 55 51](https://cloud.githubusercontent.com/assets/772616/11444863/873e6a20-9538-11e5-85b7-a8dfb4264b2f.png)

**Comment by kravets-levko** [comment]
@danfowler Does `APPROVED` field contain some other values in addition to 0? App is detecting type of column based on 1000 first rows of the file. I think there are some non-integer values (maybe, empty strings or some like that), so json-table-schema is detecting `boolean` type (0 and "" can be treat as boolean), `string` ("0" and "" respectively), and `any`. Can you check data by yourself or provide link to source file?

**Comment by danfowler** [comment]
@kravets-levko 437 values in APPROVED are greater than 1.  I don't see any empty strings.

Link: https://raw.githubusercontent.com/os-data/boost-rio-grande-do-sul-revenue/master/data/boost-rs-state-revenue-2004-2013.csv

**Comment by kravets-levko** [comment]
Hm, looks that data is valid. I'll look at this bug ASAP

**Comment by pwalsh** [comment]
@kravets-levko can look at this too
