### ISSUE TITLE
Multiple Amount concepts

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-packager#34]
Mapping multiple fields to the Amount concept creates a datapackage.json in which multiple measures have "amount" as the value for `name`.  The `name` for a measure should probably be unique among measures (c.f. `name` in a [JTS](http://dataprotocols.org/json-table-schema/#field-descriptors) resource).  There is no action to take just yet as this uniqueness constraint is not yet specified in FDP, so I'm only flagging this here as a reminder until it is.  

    "measures": [
      {
        "name": "amount",
        "source": "REVENUE",
        "resource": "boost-rs-state-revenue-2004-2013",
        "currency": "USD"
      },
      {
        "name": "amount",
        "source": "BALANCE",
        "resource": "boost-rs-state-revenue-2004-2013",
        "currency": "USD"
      }
    ],

**Comment by pwalsh** [comment]
A practical example of why measures and dimensions are better served by an object, not an array, in the spec. See: https://github.com/openspending/fiscal-data-package/issues/48#issuecomment-158681781

Levko, no action for you here until we get some treatment in the spec.

**Comment by pwalsh** [comment]
@kravets-levko with #39 please ensure that this is now fixed.
