### ISSUE TITLE
Mapping multiple columns to the same dimension concept

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-packager#35]
If I map two columns to the same dimension concept/type, they are grouped into the same dimension.  However, it should be possible to have multiple dimensions with the same dimension type.  Lots of budget datasets can have distinct classification dimensions, but distinguished by classification type (e.g. functional, administrative, or economic): http://fiscal.dataprotocols.org/spec/#classifications

![screen shot 2015-11-30 at 18 09 56](https://cloud.githubusercontent.com/assets/772616/11475297/a4565bc0-978d-11e5-87c5-c601fad0e220.png)

**Comment by danfowler** [comment]
To make it explicit, if I map two columns to the same dimension concept/type, and that dimension concept/type happens to be "classification" then there should be a further "classificationType" that distinguishes the two dimensions.  For example, I can choose to have `ADMIN1` and `ECON1` be of dimensionType `classification`, but `ADMIN1` should have a `classificationType` of "administrative" and `ECON1` should have a `classificationType` of "economic", making them two dimensions.

**Comment by pwalsh** [comment]
@danfowler thanks for the clarification. This will be addressed in the next iteration:

![Step 2 Iteration 2](https://docs.google.com/drawings/d/1plpfWsyMpMmKCHREb58i-Vo8zDDF5kNQGnC4itAJNqo/pub?w=964&h=871)

**Comment by pwalsh** [comment]
DONE!
